server {
    listen 80;

    server_name _;

    root /usr/share/nginx/html;

    index index.html;


    # ==========================================
    # React / Vite SPA
    # ==========================================
    location / {
        try_files $uri $uri/ /index.html;
    }


    # ==========================================
    # Static Assets
    # ==========================================
    location /assets/ {
        expires 1y;

        add_header Cache-Control "public, immutable";
    }


    # ==========================================
    # PWA
    # ==========================================
    location = /manifest.json {
        add_header Cache-Control "no-cache";
    }

    location = /sw.js {
        add_header Cache-Control "no-cache";
    }


    # ==========================================
    # Compression
    # ==========================================
    gzip on;

    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/json
        application/xml
        image/svg+xml;
}