// CRM Dummy Data untuk populate database
// Data ini sesuai dengan interface Karyawan, Client, dan Partner

export const karyawanDummyData = [
  {
    id: "KRY001",
    nik: "EMP2024001",
    nama_lengkap: "Ahmad Rizki Pratama",
    tempat_lahir: "Jakarta",
    tanggal_lahir: "1990-05-15",
    jenis_kelamin: "Laki-laki",
    alamat: "Jl. Sudirman No. 123, Jakarta Pusat",
    nomor_wa: "081234567890",
    email_pribadi: "ahmad.rizki.personal@gmail.com",
    divisi: "Sales & Marketing",
    jabatan: "Senior Sales Manager",
    level_jabatan: "Manager",
    status_karyawan: "Tetap",
    tanggal_bergabung: "2020-01-15",
    nama_atasan: "Direktur Sales",
    npwp: "12.345.678.9-012.000",
    nomor_rekening: "1234567890",
    nama_bank: "BCA",
    bpjs_ketenagakerjaan: "BP1234567890",
    bpjs_kesehatan: "0001234567890",
    email_kantor: "ahmad.rizki@company.com",
    nda_signed: true,
    tanggal_nda: "2020-01-10",
    level_akses: "Manager Level",
    aset_perusahaan: "Laptop Dell XPS 15, iPhone 14 Pro",
  },
  {
    id: "KRY002",
    nik: "EMP2024002",
    nama_lengkap: "Siti Nurhaliza",
    tempat_lahir: "Bandung",
    tanggal_lahir: "1992-08-22",
    jenis_kelamin: "Perempuan",
    alamat: "Jl. Gatot Subroto No. 45, Jakarta Selatan",
    nomor_wa: "081345678901",
    email_pribadi: "siti.nurhaliza88@gmail.com",
    divisi: "Sales & Marketing",
    jabatan: "Account Executive",
    level_jabatan: "Staff",
    status_karyawan: "Tetap",
    tanggal_bergabung: "2021-03-20",
    nama_atasan: "Ahmad Rizki Pratama",
    npwp: "12.345.678.9-013.000",
    nomor_rekening: "1234567891",
    nama_bank: "Mandiri",
    bpjs_ketenagakerjaan: "BP1234567891",
    bpjs_kesehatan: "0001234567891",
    email_kantor: "siti.nurhaliza@company.com",
    nda_signed: true,
    tanggal_nda: "2021-03-15",
    level_akses: "Staff Level",
    aset_perusahaan: "Laptop Asus VivoBook, Smartphone Samsung",
  },
  {
    id: "KRY003",
    nik: "EMP2024003",
    nama_lengkap: "Budi Santoso",
    tempat_lahir: "Surabaya",
    tanggal_lahir: "1988-11-30",
    jenis_kelamin: "Laki-laki",
    alamat: "Jl. Rasuna Said No. 78, Jakarta Selatan",
    nomor_wa: "081456789012",
    email_pribadi: "budi.santoso.tech@gmail.com",
    divisi: "IT Developer",
    jabatan: "Solution Architect",
    level_jabatan: "Senior Staff",
    status_karyawan: "Tetap",
    tanggal_bergabung: "2019-06-10",
    nama_atasan: "CTO",
    npwp: "12.345.678.9-014.000",
    nomor_rekening: "1234567892",
    nama_bank: "BNI",
    bpjs_ketenagakerjaan: "BP1234567892",
    bpjs_kesehatan: "0001234567892",
    email_kantor: "budi.santoso@company.com",
    nda_signed: true,
    tanggal_nda: "2019-06-05",
    level_akses: "Technical Lead",
    aset_perusahaan: "Laptop MacBook Pro 16, iPad Pro, iPhone 13",
  },
  {
    id: "KRY004",
    nik: "EMP2024004",
    nama_lengkap: "Dewi Anggraini",
    tempat_lahir: "Yogyakarta",
    tanggal_lahir: "1994-03-18",
    jenis_kelamin: "Perempuan",
    alamat: "Jl. Thamrin No. 56, Jakarta Pusat",
    nomor_wa: "081567890123",
    email_pribadi: "dewi.anggraini@gmail.com",
    divisi: "Customer Success",
    jabatan: "Customer Success Manager",
    level_jabatan: "Manager",
    status_karyawan: "Kontrak",
    tanggal_bergabung: "2022-09-01",
    nama_atasan: "Head of Customer Success",
    npwp: "12.345.678.9-015.000",
    nomor_rekening: "1234567893",
    nama_bank: "BCA",
    bpjs_ketenagakerjaan: "BP1234567893",
    bpjs_kesehatan: "0001234567893",
    email_kantor: "dewi.anggraini@company.com",
    nda_signed: true,
    tanggal_nda: "2022-08-25",
    level_akses: "Manager Level",
    aset_perusahaan: "Laptop HP EliteBook, iPhone 12",
  },
  {
    id: "KRY005",
    nik: "EMP2024005",
    nama_lengkap: "Rendra Mahendra",
    tempat_lahir: "Semarang",
    tanggal_lahir: "1991-07-25",
    jenis_kelamin: "Laki-laki",
    alamat: "Jl. Kuningan No. 99, Jakarta Selatan",
    nomor_wa: "081678901234",
    email_pribadi: "rendra.mahendra@yahoo.com",
    divisi: "Sales & Marketing",
    jabatan: "Business Development",
    level_jabatan: "Senior Staff",
    status_karyawan: "Tetap",
    tanggal_bergabung: "2021-11-15",
    nama_atasan: "Ahmad Rizki Pratama",
    npwp: "12.345.678.9-016.000",
    nomor_rekening: "1234567894",
    nama_bank: "Mandiri",
    bpjs_ketenagakerjaan: "BP1234567894",
    bpjs_kesehatan: "0001234567894",
    email_kantor: "rendra.mahendra@company.com",
    nda_signed: true,
    tanggal_nda: "2021-11-10",
    level_akses: "Senior Staff Level",
    aset_perusahaan: "Laptop Lenovo ThinkPad, Smartphone Xiaomi",
  },
];

export const clientDummyData = [
  {
    id: "CLI001",
    nama_entitas: "RS Harapan Sehat",
    kategori_client: "Rumah Sakit",
    alamat_lengkap: "Jl. Sudirman Kav. 52, Jakarta Pusat 10210",
    koordinat_gps: "-6.2088, 106.8456",
    nomor_telepon: "021-5551234",
    email_resmi: "info@rsharapansehat.com",
    id_satusehat: "RSU-DKI-001-2023",
    id_faskes_bpjs: "0112R001",
    status_akreditasi: "Paripurna",
    sistem_lama: "Manual + Excel",
    volume_pasien: "1500 pasien/bulan",
    jumlah_tempat_tidur: "250",
    nama_pic: "Dr. Michael Hartono",
    jabatan_pic: "Direktur Utama",
    whatsapp_pic: "081234567890",
    status_hubungan: "Active Client",
    paket_aktif: "HMS Enterprise",
    modul_tambahan: "Telemedicine, Mobile App",
    status_kontrak: "Aktif",
    tanggal_mulai_langganan: "2023-02-15",
    tanggal_habis_kontrak: "2026-02-15",
    total_nilai_kontrak: "Rp 850.000.000/tahun",
    file_kontrak_digital: "kontrak_RS_Harapan_Sehat_2023.pdf",
    status_esign: "Signed",
    npwp_faskes: "01.234.567.8-901.000",
  },
  {
    id: "CLI002",
    nama_entitas: "Klinik Medika Prima",
    kategori_client: "Klinik",
    alamat_lengkap: "Jl. Gatot Subroto No. 88, Jakarta Selatan 12930",
    koordinat_gps: "-6.2297, 106.8254",
    nomor_telepon: "021-5552345",
    email_resmi: "admin@medikaprima.com",
    id_satusehat: "KLN-DKI-045-2023",
    id_faskes_bpjs: "0112K045",
    status_akreditasi: "Pratama",
    sistem_lama: "Software Lokal",
    volume_pasien: "450 pasien/bulan",
    jumlah_tempat_tidur: "20",
    nama_pic: "Dr. Kartika Dewi",
    jabatan_pic: "Pemilik & Dokter Penanggung Jawab",
    whatsapp_pic: "081345678901",
    status_hubungan: "Active Client",
    paket_aktif: "Clinic Management Standard",
    modul_tambahan: "E-Prescription",
    status_kontrak: "Aktif",
    tanggal_mulai_langganan: "2023-06-20",
    tanggal_habis_kontrak: "2025-06-20",
    total_nilai_kontrak: "Rp 180.000.000/tahun",
    file_kontrak_digital: "kontrak_Klinik_Medika_Prima_2023.pdf",
    status_esign: "Signed",
    npwp_faskes: "01.234.567.8-902.000",
  },
  {
    id: "CLI003",
    nama_entitas: "Puskesmas Cempaka Putih",
    kategori_client: "Puskesmas",
    alamat_lengkap: "Jl. Cempaka Putih Tengah No. 1, Jakarta Pusat 10510",
    koordinat_gps: "-6.1751, 106.8650",
    nomor_telepon: "021-4244537",
    email_resmi: "puskesmas.cempakaputih@jakarta.go.id",
    id_satusehat: "PKM-DKI-078-2024",
    id_faskes_bpjs: "0112P078",
    status_akreditasi: "Madya",
    sistem_lama: "P-Care BPJS Manual",
    volume_pasien: "3000 pasien/bulan",
    jumlah_tempat_tidur: "10",
    nama_pic: "dr. Susilo Bambang",
    jabatan_pic: "Kepala Puskesmas",
    whatsapp_pic: "081456789012",
    status_hubungan: "Hot",
    paket_aktif: "Trial - Puskesmas Digital",
    modul_tambahan: "BPJS Integration",
    status_kontrak: "Trial",
    tanggal_mulai_langganan: "2025-01-10",
    tanggal_habis_kontrak: "2025-03-10",
    total_nilai_kontrak: "Rp 0 (Trial)",
    file_kontrak_digital: "trial_agreement_puskesmas.pdf",
    status_esign: "Pending",
    npwp_faskes: "00.000.111.1-078.000",
  },
  {
    id: "CLI004",
    nama_entitas: "Laboratorium Diagnostik Utama",
    kategori_client: "Faskes Lainnya",
    alamat_lengkap: "Jl. Rasuna Said Kav. 12, Jakarta Selatan 12940",
    koordinat_gps: "-6.2241, 106.8398",
    nomor_telepon: "021-5554567",
    email_resmi: "cs@labdiagnostik.com",
    id_satusehat: "LAB-DKI-023-2024",
    id_faskes_bpjs: "0112L023",
    status_akreditasi: "Terakreditasi ISO 15189",
    sistem_lama: "LIS Custom Build",
    volume_pasien: "2500 sampel/bulan",
    jumlah_tempat_tidur: "0",
    nama_pic: "Dr. Bambang Suryanto",
    jabatan_pic: "Medical Director",
    whatsapp_pic: "081567890123",
    status_hubungan: "Active Client",
    paket_aktif: "LIS Professional",
    modul_tambahan: "Patient Portal, API Integration",
    status_kontrak: "Aktif",
    tanggal_mulai_langganan: "2024-03-10",
    tanggal_habis_kontrak: "2025-03-10",
    total_nilai_kontrak: "Rp 420.000.000/tahun",
    file_kontrak_digital: "kontrak_Lab_Diagnostik_2024.pdf",
    status_esign: "Signed",
    npwp_faskes: "01.234.567.8-904.000",
  },
  {
    id: "CLI005",
    nama_entitas: "Medical Center Indonesia",
    kategori_client: "Rumah Sakit",
    alamat_lengkap: "Jl. Kuningan Barat No. 77, Jakarta Selatan 12710",
    koordinat_gps: "-6.2382, 106.8206",
    nomor_telepon: "021-5555678",
    email_resmi: "contact@medicalcenter.co.id",
    id_satusehat: "RSK-DKI-012-2022",
    id_faskes_bpjs: "0112R012",
    status_akreditasi: "Paripurna",
    sistem_lama: "HMS Legacy System",
    volume_pasien: "2000 pasien/bulan",
    jumlah_tempat_tidur: "180",
    nama_pic: "Prof. Dr. Andri Wijaya",
    jabatan_pic: "CEO & Medical Director",
    whatsapp_pic: "081678901234",
    status_hubungan: "Active Client",
    paket_aktif: "HMS Enterprise Plus",
    modul_tambahan: "Analytics Dashboard, AI Diagnostics",
    status_kontrak: "Aktif",
    tanggal_mulai_langganan: "2022-11-05",
    tanggal_habis_kontrak: "2025-11-05",
    total_nilai_kontrak: "Rp 1.200.000.000/tahun",
    file_kontrak_digital: "kontrak_MCI_2022.pdf",
    status_esign: "Signed",
    npwp_faskes: "01.234.567.8-905.000",
  },
  {
    id: "CLI006",
    nama_entitas: "RS Bunda Sejahtera",
    kategori_client: "Rumah Sakit",
    alamat_lengkap: "Jl. M.H. Thamrin No. 123, Jakarta Pusat 10230",
    koordinat_gps: "-6.1944, 106.8229",
    nomor_telepon: "021-3901234",
    email_resmi: "info@rsbundasejahtera.com",
    id_satusehat: "RSU-DKI-034-2024",
    id_faskes_bpjs: "0112R034",
    status_akreditasi: "Utama",
    sistem_lama: "HMS Version 1.0",
    volume_pasien: "1200 pasien/bulan",
    jumlah_tempat_tidur: "150",
    nama_pic: "dr. Lestari Widyawati, Sp.OG",
    jabatan_pic: "Direktur Medis",
    whatsapp_pic: "081789012345",
    status_hubungan: "Warm",
    paket_aktif: "None",
    modul_tambahan: "None",
    status_kontrak: "Negosiasi",
    tanggal_mulai_langganan: "",
    tanggal_habis_kontrak: "",
    total_nilai_kontrak: "Proposal: Rp 650.000.000/tahun",
    file_kontrak_digital: "proposal_RS_Bunda_Sejahtera.pdf",
    status_esign: "Pending",
    npwp_faskes: "01.234.567.8-906.000",
  },
  {
    id: "CLI007",
    nama_entitas: "Klinik Pratama Sehat Bersama",
    kategori_client: "Klinik",
    alamat_lengkap: "Jl. Tebet Raya No. 34, Jakarta Selatan 12810",
    koordinat_gps: "-6.2353, 106.8577",
    nomor_telepon: "021-8304567",
    email_resmi: "admin@sehatbersama.id",
    id_satusehat: "KLN-DKI-089-2024",
    id_faskes_bpjs: "0112K089",
    status_akreditasi: "Pratama",
    sistem_lama: "Manual",
    volume_pasien: "300 pasien/bulan",
    jumlah_tempat_tidur: "0",
    nama_pic: "dr. Hendra Gunawan",
    jabatan_pic: "Kepala Klinik",
    whatsapp_pic: "081890123456",
    status_hubungan: "Active Client",
    paket_aktif: "Clinic Management Basic",
    modul_tambahan: "None",
    status_kontrak: "Aktif",
    tanggal_mulai_langganan: "2024-08-01",
    tanggal_habis_kontrak: "2025-08-01",
    total_nilai_kontrak: "Rp 96.000.000/tahun",
    file_kontrak_digital: "kontrak_Sehat_Bersama_2024.pdf",
    status_esign: "Signed",
    npwp_faskes: "01.234.567.8-907.000",
  },
  {
    id: "CLI008",
    nama_entitas: "Apotek K-24 Mangga Dua",
    kategori_client: "Faskes Lainnya",
    alamat_lengkap: "Jl. Mangga Dua Raya No. 88, Jakarta Utara 14430",
    koordinat_gps: "-6.1398, 106.8217",
    nomor_telepon: "021-6123456",
    email_resmi: "k24manggadua@email.com",
    id_satusehat: "APT-DKI-156-2024",
    id_faskes_bpjs: "0112A156",
    status_akreditasi: "Certified",
    sistem_lama: "POS Manual",
    volume_pasien: "800 transaksi/bulan",
    jumlah_tempat_tidur: "0",
    nama_pic: "Apt. Rini Kartika",
    jabatan_pic: "Apoteker Penanggung Jawab",
    whatsapp_pic: "081901234567",
    status_hubungan: "Active Client",
    paket_aktif: "Pharmacy Management Standard",
    modul_tambahan: "E-Prescription Integration",
    status_kontrak: "Aktif",
    tanggal_mulai_langganan: "2024-05-15",
    tanggal_habis_kontrak: "2025-05-15",
    total_nilai_kontrak: "Rp 72.000.000/tahun",
    file_kontrak_digital: "kontrak_K24_Mangga_Dua_2024.pdf",
    status_esign: "Signed",
    npwp_faskes: "01.234.567.8-908.000",
  },
  {
    id: "CLI009",
    nama_entitas: "Puskesmas Kelapa Gading",
    kategori_client: "Puskesmas",
    alamat_lengkap: "Jl. Boulevard Raya No. 1, Kelapa Gading, Jakarta Utara 14240",
    koordinat_gps: "-6.1564, 106.9052",
    nomor_telepon: "021-4587123",
    email_resmi: "puskesmas.kelapagading@jakarta.go.id",
    id_satusehat: "PKM-DKI-112-2023",
    id_faskes_bpjs: "0112P112",
    status_akreditasi: "Utama",
    sistem_lama: "P-Care + Simpus",
    volume_pasien: "2500 pasien/bulan",
    jumlah_tempat_tidur: "12",
    nama_pic: "dr. Ratna Dewi Sartika, M.Kes",
    jabatan_pic: "Kepala Puskesmas",
    whatsapp_pic: "082012345678",
    status_hubungan: "Cold",
    paket_aktif: "None",
    modul_tambahan: "None",
    status_kontrak: "Prospek",
    tanggal_mulai_langganan: "",
    tanggal_habis_kontrak: "",
    total_nilai_kontrak: "Belum ada proposal",
    file_kontrak_digital: "",
    status_esign: "N/A",
    npwp_faskes: "00.000.111.1-112.000",
  },
  {
    id: "CLI010",
    nama_entitas: "RSU Permata Hati",
    kategori_client: "Rumah Sakit",
    alamat_lengkap: "Jl. Fatmawati No. 99, Jakarta Selatan 12420",
    koordinat_gps: "-6.2916, 106.7964",
    nomor_telepon: "021-7501234",
    email_resmi: "contact@rspermatahati.com",
    id_satusehat: "RSU-DKI-067-2024",
    id_faskes_bpjs: "0112R067",
    status_akreditasi: "Paripurna",
    sistem_lama: "HMS Enterprise (Competitor)",
    volume_pasien: "1800 pasien/bulan",
    jumlah_tempat_tidur: "200",
    nama_pic: "dr. Budi Raharjo, Sp.PD, FINASIM",
    jabatan_pic: "Direktur Utama",
    whatsapp_pic: "082123456789",
    status_hubungan: "Warm",
    paket_aktif: "Demo Scheduled",
    modul_tambahan: "None",
    status_kontrak: "Demo",
    tanggal_mulai_langganan: "",
    tanggal_habis_kontrak: "",
    total_nilai_kontrak: "Proposal: Rp 950.000.000/tahun",
    file_kontrak_digital: "proposal_RS_Permata_Hati.pdf",
    status_esign: "N/A",
    npwp_faskes: "01.234.567.8-909.000",
  },
];

export const partnerDummyData = [
  {
    id: "PTR001",
    nama_perusahaan: "Tech Solutions Indonesia",
    tipe_partner: "Reseller",
    spesialisasi: "Healthcare IT Implementation",
    account_manager_internal: "Rendra Mahendra",
    pic_partner: "Bapak Darmawan Wijaya",
    kontak_darurat: "081234987654",
    alamat_kantor: "Jl. Sudirman Kav. 25, Jakarta Pusat",
    status_kemitraan: "Active",
    masa_berlaku_mou_start: "2023-01-15",
    masa_berlaku_mou_end: "2026-01-15",
    file_mou_nda: "MOU_Tech_Solutions_2023.pdf",
    tingkat_kemitraan: "Platinum",
    api_endpoint: "https://api.techsolutions.id/webhook",
    api_key_reference: "TS_API_2023_ENCRYPTED",
    sla_requirement: "99.9% Uptime, Response < 2 hours",
    status_integrasi: "Production",
    skema_komisi: "15% Revenue Share",
    total_leads_generated: "145",
    total_revenue_contribution: "Rp 2.850.000.000",
    rekening_pembayaran: "BCA - 1234567890 (PT Tech Solutions ID)",
  },
  {
    id: "PTR002",
    nama_perusahaan: "Medika Integrator",
    tipe_partner: "Integrator",
    spesialisasi: "Hospital System Integration",
    account_manager_internal: "Ahmad Rizki Pratama",
    pic_partner: "Ibu Santi Kusuma",
    kontak_darurat: "081345987123",
    alamat_kantor: "Jl. Gatot Subroto No. 45, Jakarta Selatan",
    status_kemitraan: "Active",
    masa_berlaku_mou_start: "2023-06-01",
    masa_berlaku_mou_end: "2025-06-01",
    file_mou_nda: "MOU_Medika_Integrator_2023.pdf",
    tingkat_kemitraan: "Gold",
    api_endpoint: "https://integrate.medika.co.id/api",
    api_key_reference: "MI_API_2023_ENCRYPTED",
    sla_requirement: "99.5% Uptime, Response < 4 hours",
    status_integrasi: "Production",
    skema_komisi: "Flat Fee per Integration",
    total_leads_generated: "78",
    total_revenue_contribution: "Rp 1.420.000.000",
    rekening_pembayaran: "Mandiri - 9876543210 (PT Medika Integrator)",
  },
  {
    id: "PTR003",
    nama_perusahaan: "Healthcare Consultant Group",
    tipe_partner: "Consultant",
    spesialisasi: "Healthcare Digital Transformation",
    account_manager_internal: "Siti Nurhaliza",
    pic_partner: "Dr. Bambang Hartono",
    kontak_darurat: "081456987321",
    alamat_kantor: "Jl. Rasuna Said Kav. 12, Jakarta Selatan",
    status_kemitraan: "Active",
    masa_berlaku_mou_start: "2024-02-10",
    masa_berlaku_mou_end: "2027-02-10",
    file_mou_nda: "MOU_HCG_2024.pdf",
    tingkat_kemitraan: "Platinum",
    api_endpoint: "N/A",
    api_key_reference: "N/A",
    sla_requirement: "Project-based SLA",
    status_integrasi: "N/A",
    skema_komisi: "Referral Fee 10%",
    total_leads_generated: "234",
    total_revenue_contribution: "Rp 4.680.000.000",
    rekening_pembayaran: "BNI - 5432109876 (PT HCG Indonesia)",
  },
  {
    id: "PTR004",
    nama_perusahaan: "Cloud Infrastructure Partner",
    tipe_partner: "Vendor",
    spesialisasi: "Cloud Hosting & Infrastructure",
    account_manager_internal: "Budi Santoso",
    pic_partner: "Bapak Hendra Gunawan",
    kontak_darurat: "081567321098",
    alamat_kantor: "Jl. TB Simatupang Kav. 88, Jakarta Selatan",
    status_kemitraan: "Active",
    masa_berlaku_mou_start: "2022-09-01",
    masa_berlaku_mou_end: "2025-09-01",
    file_mou_nda: "MOU_Cloud_Infra_2022.pdf",
    tingkat_kemitraan: "Gold",
    api_endpoint: "https://cloud-api.infrapartner.com",
    api_key_reference: "CIP_API_2022_ENCRYPTED",
    sla_requirement: "99.99% Uptime, 24/7 Support",
    status_integrasi: "Production",
    skema_komisi: "Cost Plus Margin",
    total_leads_generated: "12",
    total_revenue_contribution: "Rp 850.000.000",
    rekening_pembayaran: "BCA - 6789012345 (PT Cloud Infrastructure)",
  },
  {
    id: "PTR005",
    nama_perusahaan: "Medical Device Supplier",
    tipe_partner: "Vendor",
    spesialisasi: "Medical Equipment & Devices",
    account_manager_internal: "Dewi Anggraini",
    pic_partner: "Ibu Ratna Sari",
    kontak_darurat: "081678654321",
    alamat_kantor: "Jl. Panjang No. 77, Jakarta Barat",
    status_kemitraan: "Active",
    masa_berlaku_mou_start: "2023-11-20",
    masa_berlaku_mou_end: "2026-11-20",
    file_mou_nda: "MOU_Medical_Device_2023.pdf",
    tingkat_kemitraan: "Silver",
    api_endpoint: "N/A",
    api_key_reference: "N/A",
    sla_requirement: "Delivery within 14 days",
    status_integrasi: "N/A",
    skema_komisi: "Bundle Deal",
    total_leads_generated: "45",
    total_revenue_contribution: "Rp 620.000.000",
    rekening_pembayaran: "Mandiri - 3456789012 (PT Medical Device Supply)",
  },
  {
    id: "PTR006",
    nama_perusahaan: "Data Analytics Pro",
    tipe_partner: "Integrator",
    spesialisasi: "Healthcare Analytics & BI",
    account_manager_internal: "Rendra Mahendra",
    pic_partner: "Bapak Arif Rahman",
    kontak_darurat: "081789321456",
    alamat_kantor: "Jl. Kuningan Barat No. 45, Jakarta Selatan",
    status_kemitraan: "Active",
    masa_berlaku_mou_start: "2024-04-01",
    masa_berlaku_mou_end: "2027-04-01",
    file_mou_nda: "MOU_Data_Analytics_2024.pdf",
    tingkat_kemitraan: "Platinum",
    api_endpoint: "https://analytics.datapro.id/api",
    api_key_reference: "DAP_API_2024_ENCRYPTED",
    sla_requirement: "99.9% Uptime, Real-time sync",
    status_integrasi: "Production",
    skema_komisi: "Percentage",
    total_leads_generated: "98",
    total_revenue_contribution: "Rp 1.960.000.000",
    rekening_pembayaran: "BCA - 7890123456 (PT Data Analytics Pro)",
  },
  {
    id: "PTR007",
    nama_perusahaan: "Security Solutions Asia",
    tipe_partner: "Vendor",
    spesialisasi: "Cybersecurity & Data Protection",
    account_manager_internal: "Budi Santoso",
    pic_partner: "Bapak Teguh Santoso",
    kontak_darurat: "081890654123",
    alamat_kantor: "Jl. HR Rasuna Said Kav. 3, Jakarta Selatan",
    status_kemitraan: "Active",
    masa_berlaku_mou_start: "2023-07-15",
    masa_berlaku_mou_end: "2026-07-15",
    file_mou_nda: "MOU_Security_Solutions_2023.pdf",
    tingkat_kemitraan: "Gold",
    api_endpoint: "https://security-api.ssa.asia",
    api_key_reference: "SSA_API_2023_ENCRYPTED",
    sla_requirement: "24/7 Monitoring, Incident response < 1 hour",
    status_integrasi: "Production",
    skema_komisi: "Fixed Annual Fee",
    total_leads_generated: "23",
    total_revenue_contribution: "Rp 480.000.000",
    rekening_pembayaran: "Mandiri - 2109876543 (PT Security Solutions Asia)",
  },
  {
    id: "PTR008",
    nama_perusahaan: "Training & Development Institute",
    tipe_partner: "Consultant",
    spesialisasi: "Healthcare Staff Training & Certification",
    account_manager_internal: "Dewi Anggraini",
    pic_partner: "Ibu Maya Puspita",
    kontak_darurat: "082001234567",
    alamat_kantor: "Jl. Thamrin No. 66, Jakarta Pusat",
    status_kemitraan: "Active",
    masa_berlaku_mou_start: "2024-01-10",
    masa_berlaku_mou_end: "2027-01-10",
    file_mou_nda: "MOU_Training_Institute_2024.pdf",
    tingkat_kemitraan: "Silver",
    api_endpoint: "N/A",
    api_key_reference: "N/A",
    sla_requirement: "Training schedule confirmation within 3 days",
    status_integrasi: "N/A",
    skema_komisi: "Revenue Share per Training Session",
    total_leads_generated: "156",
    total_revenue_contribution: "Rp 780.000.000",
    rekening_pembayaran: "BNI - 8901234567 (Yayasan Training Institute)",
  },
  {
    id: "PTR009",
    nama_perusahaan: "Mobile App Developer Studio",
    tipe_partner: "Integrator",
    spesialisasi: "Mobile Healthcare Applications",
    account_manager_internal: "Ahmad Rizki Pratama",
    pic_partner: "Bapak Rizky Pratama",
    kontak_darurat: "082112345678",
    alamat_kantor: "Jl. BSD Green Office Park, Tangerang",
    status_kemitraan: "Inactive",
    masa_berlaku_mou_start: "2022-03-01",
    masa_berlaku_mou_end: "2025-03-01",
    file_mou_nda: "MOU_Mobile_App_2022.pdf",
    tingkat_kemitraan: "Silver",
    api_endpoint: "https://mobile-api.appstudio.id",
    api_key_reference: "MAS_API_2022_ENCRYPTED",
    sla_requirement: "App update within 48 hours",
    status_integrasi: "Staging",
    skema_komisi: "Project-based Fee",
    total_leads_generated: "34",
    total_revenue_contribution: "Rp 510.000.000",
    rekening_pembayaran: "BCA - 1357924680 (PT Mobile App Studio)",
  },
  {
    id: "PTR010",
    nama_perusahaan: "Global Tech AI Solutions",
    tipe_partner: "Vendor",
    spesialisasi: "AI & Machine Learning for Healthcare",
    account_manager_internal: "Budi Santoso",
    pic_partner: "Mr. Jonathan Lee",
    kontak_darurat: "+65-9123-4567",
    alamat_kantor: "Singapore Office - Representative in Jakarta",
    status_kemitraan: "Active",
    masa_berlaku_mou_start: "2024-06-01",
    masa_berlaku_mou_end: "2027-06-01",
    file_mou_nda: "MOU_Global_Tech_AI_2024.pdf",
    tingkat_kemitraan: "Platinum",
    api_endpoint: "https://ai-api.globaltech.sg/v2",
    api_key_reference: "GT_AI_API_2024_ENCRYPTED",
    sla_requirement: "99.99% Uptime, <50ms latency",
    status_integrasi: "Production",
    skema_komisi: "Percentage",
    total_leads_generated: "62",
    total_revenue_contribution: "Rp 3.720.000.000",
    rekening_pembayaran: "HSBC Singapore - USD Account",
  },
];

export const opportunityDummyData = [
  {
    id: "OPP-001",
    name: "HMS Enterprise Implementation - RS Harapan Sehat",
    clientName: "RS Harapan Sehat",
    contactPerson: "Dr. Michael Hartono",
    email: "michael.hartono@rsharapansehat.com",
    phone: "081234567890",
    products: [
      {
        productId: "PROD-001",
        productName: "HMS Enterprise License",
        quantity: 1,
        unitPrice: 500000000,
        totalPrice: 500000000
      },
      {
        productId: "PROD-002",
        productName: "Implementation Service",
        quantity: 1,
        unitPrice: 150000000,
        totalPrice: 150000000
      },
      {
        productId: "PROD-003",
        productName: "Training Package",
        quantity: 1,
        unitPrice: 50000000,
        totalPrice: 50000000
      }
    ],
    totalValue: 700000000,
    currency: "IDR",
    probability: 75,
    createdDate: "2024-12-01",
    closeDate: "2025-03-31",
    stage: "negotiation",
    status: "open",
    ownerName: "Ahmad Rizki Pratama",
    source: "Direct Sales",
    description: "Full HMS Enterprise implementation for 250-bed hospital with telemedicine and mobile app modules",
    notes: "Client is very interested, waiting for board approval on budget",
    nextFollowUpDate: "2025-01-30",
    reminderSent: false,
    activities: [
      {
        id: "ACT-001",
        type: "meeting",
        description: "Initial presentation with board of directors",
        createdAt: "2024-12-05",
        createdBy: "Ahmad Rizki Pratama"
      },
      {
        id: "ACT-002",
        type: "proposal",
        description: "Sent detailed proposal and pricing",
        createdAt: "2024-12-15",
        createdBy: "Ahmad Rizki Pratama"
      }
    ],
    opportunityMaturity: {
      selected: true,
      funded: true,
      timeline: true
    },
    target: "Q1",
    targetYear: "2025",
    closingTarget: "2025-03-31",
    forecastType: "Forecast/Commit",
    lowHangingFruit: false,
    solution: "HMS Enterprise + Telemedicine + Mobile App",
    product: "HMS Enterprise",
    existingSystem: "Manual + Excel",
    competitor: "Competitor A",
    competitorWebsite: "https://competitor-a.com",
    partnerName: "Tech Solutions Indonesia",
    partnerId: "PTR001",
    salesRep: "Ahmad Rizki Pratama",
    salesRepId: "KRY001",
    bizmod: "Annual Subscription",
    annualRevenue: 700000000,
    sizeOfDeal: 700000000,
    monthlyRev: 58333333,
    salesStage: "Align",
    winProbability: 75,
    currentStatus: "Waiting for board meeting approval on Jan 28",
    nextAction: "Follow up after board meeting, prepare contract draft",
    timestamps: {
      currentStatus: "20 Jan 2026, 09:30",
      nextAction: "20 Jan 2026, 09:35",
      notes: "19 Jan 2026, 14:20"
    },
    fieldHistory: {
      currentStatus: [
        { value: "Initial contact made with Dr. Michael", timestamp: "1 Des 2024, 10:15" },
        { value: "Proposal sent to board of directors", timestamp: "5 Des 2024, 14:30" },
        { value: "Board scheduled meeting for Jan 28", timestamp: "15 Jan 2026, 09:00" },
        { value: "Waiting for board meeting approval on Jan 28", timestamp: "20 Jan 2026, 09:30" }
      ],
      nextAction: [
        { value: "Schedule follow-up call", timestamp: "1 Des 2024, 10:20" },
        { value: "Prepare detailed technical proposal", timestamp: "5 Des 2024, 14:35" },
        { value: "Follow up after board meeting, prepare contract draft", timestamp: "20 Jan 2026, 09:35" }
      ],
      notes: [
        { value: "Client is very interested, waiting for board approval on budget", timestamp: "19 Jan 2026, 14:20" }
      ],
      solution: [
        { value: "HMS Enterprise", timestamp: "1 Des 2024, 10:30" },
        { value: "HMS Enterprise + Telemedicine", timestamp: "10 Des 2024, 15:00" },
        { value: "HMS Enterprise + Telemedicine + Mobile App", timestamp: "15 Jan 2026, 09:15" }
      ],
      product: [
        { value: "HMS Enterprise", timestamp: "1 Des 2024, 10:30" }
      ],
      existingSystem: [
        { value: "Manual + Excel", timestamp: "1 Des 2024, 11:00" }
      ],
      competitor: [
        { value: "None identified", timestamp: "1 Des 2024, 11:30" },
        { value: "Competitor A", timestamp: "20 Des 2024, 14:00" }
      ],
      bizmod: [],
      managerNotes: [
        { value: "Large opportunity - needs board approval", timestamp: "5 Des 2024, 16:00" },
        { value: "High priority deal - strategic account", timestamp: "15 Jan 2026, 10:00" }
      ],
      actionsToClose: [
        { value: "Get budget approval, finalize contract terms", timestamp: "10 Des 2024, 14:00" },
        { value: "Get budget approval, finalize contract terms, schedule implementation kickoff", timestamp: "18 Jan 2026, 11:30" }
      ],
      engineerNotes: [
        { value: "Need to validate technical requirements with IT team", timestamp: "8 Des 2024, 09:00" },
        { value: "Technical validation completed, no major concerns", timestamp: "22 Des 2024, 15:30" }
      ],
      whyBuyAnything: [
        { value: "Current manual system causing inefficiencies", timestamp: "1 Des 2024, 14:00" },
        { value: "Current manual system causing inefficiencies and data errors", timestamp: "10 Des 2024, 11:20" }
      ],
      whyBuyNow: [
        { value: "Board wants to digitalize by end of year", timestamp: "1 Des 2024, 14:15" },
        { value: "New regulation requires digital integration by Q2 2025", timestamp: "15 Des 2024, 10:00" }
      ],
      whyBuyIntramedika: [
        { value: "Best integration with SatuSehat", timestamp: "5 Des 2024, 15:00" },
        { value: "Best integration with SatuSehat, comprehensive feature set", timestamp: "20 Des 2024, 09:30" }
      ],
      winStrategyBuyingProcess: [
        { value: "Focus on compliance", timestamp: "8 Des 2024, 16:00" },
        { value: "Focus on compliance and integration capabilities", timestamp: "18 Jan 2026, 09:45" }
      ],
      jointExecutionPlanCreated: [
        { value: "Q1 2025 Implementation Plan", timestamp: "15 Jan 2026, 14:00" }
      ],
      risk: [
        { value: "Budget approval may be delayed", timestamp: "10 Des 2024, 16:30" },
        { value: "Budget approval delay if board meeting postponed", timestamp: "15 Jan 2026, 11:00" }
      ],
      annualRevenue: [
        { value: "200000000", timestamp: "1 Des 2024, 10:00" },
        { value: "250000000", timestamp: "10 Des 2024, 14:30" },
        { value: "300000000", timestamp: "15 Jan 2026, 09:00" }
      ],
      sizeOfDeal: [
        { value: "300000000", timestamp: "1 Des 2024, 10:00" },
        { value: "350000000", timestamp: "15 Jan 2026, 09:00" }
      ],
      monthlyRev: [
        { value: "8333333", timestamp: "10 Des 2024, 14:35" },
        { value: "10000000", timestamp: "15 Jan 2026, 09:05" }
      ]
    },
    managerNotes: "High priority deal - strategic account",
    actionsToClose: "Get budget approval, finalize contract terms, schedule implementation kickoff",
    engineerNotes: "Technical validation completed, no major concerns",
    whyBuyAnything: "Current manual system causing inefficiencies and data errors",
    whyBuyNow: "New regulation requires digital integration by Q2 2025",
    evaluationStarted: true,
    budgetStatus: "Approved",
    whyBuyIntramedika: "Best integration with SatuSehat, comprehensive feature set",
    winStrategyBuyingProcess: "Focus on compliance and integration capabilities",
    jointExecutionPlanCreated: "Q1 2025 Implementation Plan",
    vendorChoice: true,
    agreementStatus: "Terms & Conditions Agreed",
    customerCommit: "Commit to Sign",
    businessCaseStatus: "Business Case Validated",
    jointExecutionPlanAgreed: "Yes",
    risk: "Budget approval delay if board meeting postponed",
    functionFit: "No Gaps",
    competitiveDifferentiation: "Clear Advantage",
    solutionDemoStatus: true,
    implementationStrategy: "Strategy Known",
    solutionArchitectureValidated: true,
    implementationPlanAgreed: true,
    createdBy: "Ahmad Rizki Pratama",
    createdAt: "2024-12-01T10:00:00Z"
  },
  {
    id: "OPP-002",
    name: "Clinic Management System - Klinik Medika Prima",
    clientName: "Klinik Medika Prima",
    contactPerson: "dr. Sarah Wijaya",
    email: "sarah.wijaya@medikaprima.com",
    phone: "081345678901",
    products: [
      {
        productId: "PROD-004",
        productName: "Clinic Management System",
        quantity: 1,
        unitPrice: 120000000,
        totalPrice: 120000000
      }
    ],
    totalValue: 120000000,
    currency: "IDR",
    probability: 60,
    createdDate: "2025-01-05",
    closeDate: "2025-04-30",
    stage: "proposal",
    status: "open",
    ownerName: "Siti Nurhaliza",
    source: "Referral",
    description: "Complete clinic management solution for multi-location clinic",
    notes: "Client comparing with 2 other vendors",
    nextFollowUpDate: "2025-02-05",
    reminderSent: false,
    activities: [],
    opportunityMaturity: {
      selected: false,
      funded: true,
      timeline: false
    },
    target: "Q2",
    targetYear: "2025",
    closingTarget: "2025-04-30",
    forecastType: "Upside",
    lowHangingFruit: true,
    solution: "Clinic Management + Queue System",
    product: "Clinic Management System",
    existingSystem: "Paper-based",
    competitor: "Competitor B",
    salesRep: "Siti Nurhaliza",
    salesRepId: "KRY002",
    bizmod: "Perpetual License",
    annualRevenue: 120000000,
    sizeOfDeal: 120000000,
    salesStage: "Solution",
    winProbability: 60,
    currentStatus: "Demo scheduled for Feb 3",
    nextAction: "Conduct demo, address implementation concerns",
    timestamps: {
      currentStatus: "21 Jan 2026, 10:15",
      nextAction: "21 Jan 2026, 10:20",
      notes: null
    },
    fieldHistory: {
      currentStatus: [
        { value: "Received inquiry from website", timestamp: "5 Jan 2026, 14:45" },
        { value: "Client comparing with 2 other vendors", timestamp: "10 Jan 2026, 11:20" },
        { value: "Demo scheduled for Feb 3", timestamp: "21 Jan 2026, 10:15" }
      ],
      nextAction: [
        { value: "Send initial proposal and pricing", timestamp: "5 Jan 2026, 15:00" },
        { value: "Conduct demo, address implementation concerns", timestamp: "21 Jan 2026, 10:20" }
      ],
      notes: [],
      solution: [
        { value: "Clinic Management + Queue System", timestamp: "5 Jan 2026, 15:30" }
      ],
      product: [
        { value: "Clinic Management System", timestamp: "5 Jan 2026, 15:30" }
      ],
      existingSystem: [
        { value: "Paper-based", timestamp: "5 Jan 2026, 15:35" }
      ],
      competitor: [
        { value: "Competitor B", timestamp: "10 Jan 2026, 11:30" }
      ],
      bizmod: [],
      managerNotes: [],
      actionsToClose: [
        { value: "Conduct successful demo, address pricing concerns", timestamp: "21 Jan 2026, 10:25" }
      ],
      engineerNotes: [],
      whyBuyAnything: [
        { value: "Manual paper-based system is inefficient and error-prone", timestamp: "10 Jan 2026, 14:00" }
      ],
      whyBuyNow: [
        { value: "Owner wants to implement before Q2 2025", timestamp: "10 Jan 2026, 14:05" }
      ],
      whyBuyIntramedika: [],
      winStrategyBuyingProcess: [],
      jointExecutionPlanCreated: [],
      risk: [],
      annualRevenue: [
        { value: "120000000", timestamp: "5 Jan 2026, 15:00" }
      ],
      sizeOfDeal: [
        { value: "120000000", timestamp: "5 Jan 2026, 15:00" }
      ],
      monthlyRev: []
    },
    createdBy: "Siti Nurhaliza",
    createdAt: "2025-01-05T14:30:00Z"
  },
  {
    id: "OPP-003",
    name: "Lab Information System - Laboratorium BioMedis",
    clientName: "Laboratorium BioMedis",
    contactPerson: "Dr. Andri Kusuma",
    email: "andri.kusuma@biomedis.com",
    phone: "081456789012",
    products: [
      {
        productId: "PROD-006",
        productName: "Lab Information System",
        quantity: 1,
        unitPrice: 280000000,
        totalPrice: 280000000
      }
    ],
    totalValue: 280000000,
    currency: "IDR",
    probability: 40,
    createdDate: "2024-11-15",
    closeDate: "2025-05-31",
    stage: "prospecting",
    status: "open",
    ownerName: "Budi Santoso",
    source: "Cold Outreach",
    description: "Lab management system with equipment integration",
    notes: "Early stage, still educating client",
    nextFollowUpDate: "2025-02-10",
    reminderSent: false,
    activities: [],
    opportunityMaturity: {
      selected: false,
      funded: false,
      timeline: false
    },
    target: "Q2",
    targetYear: "2025",
    closingTarget: "2025-05-31",
    forecastType: "Pipeline",
    lowHangingFruit: false,
    solution: "LIS + Equipment Integration",
    product: "Lab Information System",
    existingSystem: "Legacy LIS (outdated)",
    salesRep: "Budi Santoso",
    salesRepId: "KRY003",
    bizmod: "Annual Subscription",
    annualRevenue: 280000000,
    sizeOfDeal: 280000000,
    salesStage: "Engage",
    winProbability: 40,
    currentStatus: "Qualifying opportunity",
    nextAction: "Schedule needs assessment meeting",
    timestamps: {
      currentStatus: "10 Jan 2026, 15:30",
      nextAction: "10 Jan 2026, 15:35",
      notes: "8 Jan 2026, 09:45"
    },
    fieldHistory: {
      currentStatus: [
        { value: "Cold outreach via email", timestamp: "15 Nov 2024, 09:30" },
        { value: "First call - interested but need more info", timestamp: "20 Nov 2024, 14:15" },
        { value: "Sent presentation deck about LIS capabilities", timestamp: "25 Nov 2024, 10:00" },
        { value: "Client reviewing our proposal", timestamp: "5 Des 2024, 16:20" },
        { value: "Follow up - still comparing with competitors", timestamp: "20 Des 2024, 11:30" },
        { value: "Qualifying opportunity", timestamp: "10 Jan 2026, 15:30" }
      ],
      nextAction: [
        { value: "Send introductory email with case studies", timestamp: "15 Nov 2024, 09:45" },
        { value: "Schedule discovery call", timestamp: "20 Nov 2024, 14:20" },
        { value: "Send detailed proposal with pricing", timestamp: "25 Nov 2024, 10:10" },
        { value: "Schedule technical demo", timestamp: "5 Des 2024, 16:25" },
        { value: "Schedule needs assessment meeting", timestamp: "10 Jan 2026, 15:35" }
      ],
      notes: [
        { value: "Client currently using legacy system that is outdated and slow. Main pain points: integration with lab equipment and reporting", timestamp: "20 Nov 2024, 14:30" },
        { value: "Budget concerns - need to justify ROI. Director will present to management in Q1 2025", timestamp: "5 Des 2024, 16:30" },
        { value: "Early stage, still educating client on modern LIS benefits vs legacy system", timestamp: "8 Jan 2026, 09:45" }
      ],
      solution: [],
      product: [],
      existingSystem: [],
      competitor: [],
      bizmod: [],
      managerNotes: [],
      actionsToClose: [],
      engineerNotes: [],
      whyBuyAnything: [],
      whyBuyNow: [],
      whyBuyIntramedika: [],
      winStrategyBuyingProcess: [],
      jointExecutionPlanCreated: [],
      risk: [],
      annualRevenue: [
        { value: "280000000", timestamp: "15 Nov 2024, 09:50" }
      ],
      sizeOfDeal: [
        { value: "280000000", timestamp: "15 Nov 2024, 09:50" }
      ],
      monthlyRev: []
    },
    createdBy: "Budi Santoso",
    createdAt: "2024-11-15T09:20:00Z"
  },
  {
    id: "OPP-004",
    name: "Pharmacy System - Apotek Sehat Sentosa (5 Branches)",
    clientName: "Apotek Sehat Sentosa",
    contactPerson: "Apt. Linda Mariana",
    email: "linda.mariana@apoteksehat.com",
    phone: "081567890123",
    products: [
      {
        productId: "PROD-008",
        productName: "Pharmacy Management System",
        quantity: 5,
        unitPrice: 25000000,
        totalPrice: 125000000
      }
    ],
    totalValue: 125000000,
    currency: "IDR",
    probability: 85,
    createdDate: "2024-10-20",
    closeDate: "2025-02-28",
    stage: "negotiation",
    status: "open",
    ownerName: "Rendra Mahendra",
    source: "Website Inquiry",
    description: "Pharmacy management for 5-branch chain",
    notes: "Contract in final review",
    nextFollowUpDate: "2025-01-25",
    reminderSent: true,
    activities: [],
    opportunityMaturity: {
      selected: true,
      funded: true,
      timeline: true
    },
    target: "Q1",
    targetYear: "2025",
    closingTarget: "2025-02-28",
    forecastType: "Forecast/Commit",
    lowHangingFruit: true,
    solution: "Pharmacy System + POS + Central Inventory",
    product: "Pharmacy Management System",
    existingSystem: "Basic POS system",
    salesRep: "Rendra Mahendra",
    salesRepId: "KRY005",
    bizmod: "Perpetual License",
    annualRevenue: 125000000,
    sizeOfDeal: 125000000,
    salesStage: "Close",
    winProbability: 85,
    currentStatus: "Contract under legal review",
    nextAction: "Follow up on contract, prepare implementation",
    timestamps: {
      currentStatus: "18 Jan 2026, 11:00",
      nextAction: "18 Jan 2026, 11:05",
      notes: "15 Jan 2026, 16:30"
    },
    fieldHistory: {
      currentStatus: [
        { value: "Website inquiry received", timestamp: "20 Okt 2024, 11:50" },
        { value: "Initial meeting conducted - very interested", timestamp: "25 Okt 2024, 14:00" },
        { value: "Site visit to 3 branches completed", timestamp: "5 Nov 2024, 10:30" },
        { value: "Demo of system at main branch", timestamp: "12 Nov 2024, 15:00" },
        { value: "Proposal sent with pricing for 5 branches", timestamp: "20 Nov 2024, 09:15" },
        { value: "Negotiation on pricing - agreed on final terms", timestamp: "10 Des 2024, 13:45" },
        { value: "Contract sent for signature", timestamp: "2 Jan 2026, 10:00" },
        { value: "Contract under legal review", timestamp: "18 Jan 2026, 11:00" }
      ],
      nextAction: [
        { value: "Schedule initial meeting", timestamp: "20 Okt 2024, 12:00" },
        { value: "Conduct site survey", timestamp: "25 Okt 2024, 14:15" },
        { value: "Prepare and send demo", timestamp: "5 Nov 2024, 10:45" },
        { value: "Send comprehensive proposal", timestamp: "12 Nov 2024, 15:20" },
        { value: "Negotiate terms and pricing", timestamp: "20 Nov 2024, 09:30" },
        { value: "Prepare contract and implementation plan", timestamp: "10 Des 2024, 14:00" },
        { value: "Follow up on contract, prepare implementation", timestamp: "18 Jan 2026, 11:05" }
      ],
      notes: [
        { value: "Client wants centralized inventory management across all 5 branches. Current POS system lacks this feature", timestamp: "25 Okt 2024, 15:00" },
        { value: "Owner is very tech-savvy and excited about the system. Main concern is training staff at all branches", timestamp: "12 Nov 2024, 16:00" },
        { value: "Contract in final review - expecting signature by end of month", timestamp: "15 Jan 2026, 16:30" }
      ],
      solution: [],
      product: [],
      existingSystem: [],
      competitor: [],
      bizmod: [],
      managerNotes: [],
      actionsToClose: [],
      engineerNotes: [],
      whyBuyAnything: [],
      whyBuyNow: [],
      whyBuyIntramedika: [],
      winStrategyBuyingProcess: [],
      jointExecutionPlanCreated: [],
      risk: [],
      annualRevenue: [
        { value: "125000000", timestamp: "20 Okt 2024, 12:15" }
      ],
      sizeOfDeal: [
        { value: "125000000", timestamp: "20 Okt 2024, 12:15" },
        { value: "120000000", timestamp: "10 Des 2024, 14:10" }
      ],
      monthlyRev: []
    },
    createdBy: "Rendra Mahendra",
    createdAt: "2024-10-20T11:45:00Z"
  },
  {
    id: "OPP-005",
    name: "Telemedicine Platform - Klinik Keluarga Sejahtera",
    clientName: "Klinik Keluarga Sejahtera",
    contactPerson: "dr. Fitri Handayani",
    email: "fitri.handayani@klinikkeluarga.com",
    phone: "081678901234",
    products: [
      {
        productId: "PROD-010",
        productName: "Telemedicine Platform",
        quantity: 1,
        unitPrice: 90000000,
        totalPrice: 90000000
      }
    ],
    totalValue: 90000000,
    currency: "IDR",
    probability: 50,
    createdDate: "2025-01-10",
    closeDate: "2025-06-30",
    stage: "proposal",
    status: "open",
    ownerName: "Ahmad Rizki Pratama",
    source: "Partner Referral",
    description: "Telemedicine platform with mobile app",
    notes: "Client concerned about user adoption",
    nextFollowUpDate: "2025-02-01",
    reminderSent: false,
    activities: [],
    opportunityMaturity: {
      selected: false,
      funded: true,
      timeline: false
    },
    target: "Q2",
    targetYear: "2025",
    closingTarget: "2025-06-30",
    forecastType: "Strong Upside",
    lowHangingFruit: false,
    solution: "Telemedicine + Mobile App",
    product: "Telemedicine Platform",
    existingSystem: "None",
    salesRep: "Ahmad Rizki Pratama",
    salesRepId: "KRY001",
    bizmod: "Annual Subscription",
    annualRevenue: 90000000,
    sizeOfDeal: 90000000,
    salesStage: "Understand",
    winProbability: 50,
    currentStatus: "Proposal submitted",
    nextAction: "Provide case studies, offer pilot",
    timestamps: {
      currentStatus: "17 Jan 2026, 16:30",
      nextAction: "17 Jan 2026, 16:35",
      notes: "16 Jan 2026, 11:45"
    },
    fieldHistory: {
      currentStatus: [
        { value: "Received referral from Healthcare Consultant Group", timestamp: "10 Jan 2026, 16:05" },
        { value: "First call with Dr. Fitri - exploring telemedicine options", timestamp: "12 Jan 2026, 14:30" },
        { value: "Sent initial proposal with platform features", timestamp: "15 Jan 2026, 10:00" },
        { value: "Proposal submitted", timestamp: "17 Jan 2026, 16:30" }
      ],
      nextAction: [
        { value: "Schedule intro call", timestamp: "10 Jan 2026, 16:10" },
        { value: "Send proposal with telemedicine features and benefits", timestamp: "12 Jan 2026, 14:45" },
        { value: "Provide case studies, offer pilot", timestamp: "17 Jan 2026, 16:35" }
      ],
      notes: [
        { value: "Client has no current system, starting from scratch. Main concern is whether patients will actually use the telemedicine platform", timestamp: "12 Jan 2026, 15:00" },
        { value: "Dr. Fitri mentioned they serve elderly patients who may not be tech-savvy. Need to emphasize user-friendly interface and training", timestamp: "15 Jan 2026, 11:00" },
        { value: "Client concerned about user adoption", timestamp: "16 Jan 2026, 11:45" }
      ],
      solution: [],
      product: [],
      existingSystem: [],
      competitor: [],
      bizmod: [],
      managerNotes: [],
      actionsToClose: [],
      engineerNotes: [],
      whyBuyAnything: [],
      whyBuyNow: [],
      whyBuyIntramedika: [],
      winStrategyBuyingProcess: [],
      jointExecutionPlanCreated: [],
      risk: [],
      annualRevenue: [
        { value: "75000000", timestamp: "12 Jan 2026, 14:50" }
      ],
      sizeOfDeal: [
        { value: "75000000", timestamp: "12 Jan 2026, 14:50" }
      ],
      monthlyRev: [
        { value: "6250000", timestamp: "12 Jan 2026, 14:55" }
      ]
    },
    createdBy: "Ahmad Rizki Pratama",
    createdAt: "2025-01-10T16:00:00Z"
  }
];