// Product Dummy Data for Healthcare HMS Catalog
export const productDummyData = [
  {
    id: "PROD-1",
    name: "HMS Enterprise Edition",
    category: "Hospital Management",
    description: "Sistem informasi manajemen rumah sakit lengkap dengan integrasi SatuSehat dan BPJS. Mendukung 500+ tempat tidur dengan performa optimal.",
    price: 500000000,
    stock: 50,
    sold: 120,
    features: [
      "Integrasi SatuSehat & BPJS",
      "Electronic Medical Record (EMR)",
      "Billing & Klaim Otomatis",
      "Apotek & Inventory Management",
      "Laboratorium & Radiologi",
      "Queue Management System",
      "Mobile App untuk Dokter & Pasien",
      "Business Intelligence Dashboard",
      "Multi-cabang Support",
      "Cloud-ready Architecture"
    ],
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-01-15T08:00:00Z"
  },
  {
    id: "PROD-2",
    name: "HMS Standard Edition",
    category: "Hospital Management",
    description: "Solusi HMS untuk rumah sakit kecil hingga menengah. Fitur lengkap dengan harga terjangkau untuk RS 50-200 tempat tidur.",
    price: 250000000,
    stock: 100,
    sold: 85,
    features: [
      "Rekam Medis Elektronik",
      "Registrasi & Admisi Pasien",
      "Rawat Jalan & Rawat Inap",
      "Farmasi & Apotek",
      "Kasir & Billing",
      "Integrasi BPJS",
      "Laporan & Analytics",
      "User Management"
    ],
    createdAt: "2024-01-10T09:30:00Z",
    updatedAt: "2024-01-10T09:30:00Z"
  },
  {
    id: "PROD-3",
    name: "LIS Pro - Laboratory Information System",
    category: "Laboratory",
    description: "Sistem informasi laboratorium terintegrasi dengan HMS. Mendukung berbagai jenis pemeriksaan lab dengan workflow otomatis.",
    price: 150000000,
    stock: 75,
    sold: 68,
    features: [
      "Order Management dari HMS/EMR",
      "Barcode & Sample Tracking",
      "Instrument Interface (LIS)",
      "Quality Control Management",
      "Result Validation Workflow",
      "Auto-verification Rules",
      "Custom Report Templates",
      "Mobile Result Access",
      "Statistical Analysis",
      "Integrasi Alat Lab Otomatis"
    ],
    createdAt: "2024-01-12T10:00:00Z",
    updatedAt: "2024-01-12T10:00:00Z"
  },
  {
    id: "PROD-4",
    name: "RIS/PACS Enterprise",
    category: "Radiology",
    description: "Radiology Information System dengan PACS (Picture Archiving and Communication System). Mendukung DICOM dan telemedicine.",
    price: 350000000,
    stock: 40,
    sold: 52,
    features: [
      "DICOM Viewer & Storage",
      "Modality Worklist (MWL)",
      "3D Reconstruction Tools",
      "Teleradiology Support",
      "Voice Recognition Reporting",
      "Cloud PACS Storage",
      "Mobile Image Viewing",
      "HL7 & FHIR Integration",
      "AI-assisted Diagnosis",
      "Multi-site Access"
    ],
    createdAt: "2024-01-08T11:15:00Z",
    updatedAt: "2024-01-08T11:15:00Z"
  },
  {
    id: "PROD-5",
    name: "Pharmacy Management System",
    category: "Pharmacy",
    description: "Sistem manajemen apotek dan farmasi rumah sakit. Inventory, resep elektronik, dan drug interaction checking.",
    price: 120000000,
    stock: 90,
    sold: 95,
    features: [
      "E-Prescribing Integration",
      "Drug Interaction Checker",
      "Inventory & Stock Management",
      "Expiry Date Tracking",
      "Automatic Reorder Point",
      "Batch & Serial Number",
      "Insurance & BPJS Integration",
      "Barcode Dispensing",
      "Drug Information Database",
      "Supplier Management"
    ],
    createdAt: "2024-01-05T13:00:00Z",
    updatedAt: "2024-01-05T13:00:00Z"
  },
  {
    id: "PROD-6",
    name: "Telemedicine Platform",
    category: "Cloud Services",
    description: "Platform telemedicine untuk konsultasi online, video call dengan dokter, dan resep digital. White-label ready.",
    price: 180000000,
    stock: 60,
    sold: 78,
    features: [
      "HD Video Consultation",
      "Appointment Scheduling",
      "E-Prescription & E-Sick Letter",
      "Payment Gateway Integration",
      "Patient Health Records",
      "Chat & File Sharing",
      "Multi-platform (Web, iOS, Android)",
      "Doctor Dashboard",
      "Rating & Review System",
      "White-label Customization"
    ],
    createdAt: "2024-01-18T14:30:00Z",
    updatedAt: "2024-01-18T14:30:00Z"
  },
  {
    id: "PROD-7",
    name: "SatuSehat Integration Module",
    category: "Integration",
    description: "Modul integrasi untuk menghubungkan HMS Anda dengan platform SatuSehat Kemenkes RI. Mandatory compliance untuk RS.",
    price: 75000000,
    stock: 150,
    sold: 142,
    features: [
      "Patient Master Index (PMI)",
      "Encounter & Visit Sync",
      "Medication Record",
      "Laboratory Result Upload",
      "Immunization Record",
      "Observation & Vital Signs",
      "Diagnostic Report",
      "OAuth2 Authentication",
      "Real-time Sync Engine",
      "Error Handling & Retry Logic"
    ],
    createdAt: "2024-01-20T15:00:00Z",
    updatedAt: "2024-01-20T15:00:00Z"
  },
  {
    id: "PROD-8",
    name: "Mobile HMS for Doctors",
    category: "Cloud Services",
    description: "Aplikasi mobile untuk dokter mengakses EMR, melihat jadwal, menulis resep, dan konsultasi telemedicine dari smartphone.",
    price: 95000000,
    stock: 80,
    sold: 110,
    features: [
      "Patient EMR Access",
      "Schedule & Appointment",
      "E-Prescribing",
      "Lab & Radiology Results",
      "Clinical Notes & SOAP",
      "Video Consultation",
      "Push Notifications",
      "Offline Mode",
      "Biometric Login",
      "iOS & Android"
    ],
    createdAt: "2024-01-22T16:00:00Z",
    updatedAt: "2024-01-22T16:00:00Z"
  },
  {
    id: "PROD-9",
    name: "Queue Management System",
    category: "Hospital Management",
    description: "Sistem antrian digital dengan display board, mobile check-in, dan notifikasi SMS. Mengurangi waktu tunggu pasien hingga 40%.",
    price: 85000000,
    stock: 70,
    sold: 88,
    features: [
      "Digital Display Board",
      "Mobile Queue Check-in",
      "SMS & WhatsApp Notification",
      "Multi-counter Support",
      "Priority Queue Management",
      "Average Wait Time Analytics",
      "Kiosk Self Check-in",
      "Voice Announcement",
      "Real-time Dashboard",
      "API Integration with HMS"
    ],
    createdAt: "2024-01-25T10:30:00Z",
    updatedAt: "2024-01-25T10:30:00Z"
  },
  {
    id: "PROD-10",
    name: "Clinical Decision Support System (CDSS)",
    category: "Hospital Management",
    description: "AI-powered sistem pendukung keputusan klinis. Memberikan rekomendasi diagnosis dan treatment berdasarkan evidence-based medicine.",
    price: 220000000,
    stock: 35,
    sold: 42,
    features: [
      "AI-assisted Diagnosis",
      "Drug Interaction Alerts",
      "Treatment Recommendations",
      "Clinical Guidelines Database",
      "Risk Stratification",
      "Allergy & Contraindication Check",
      "Lab Value Interpretation",
      "Evidence-based Protocols",
      "Real-time Clinical Alerts",
      "Machine Learning Updates"
    ],
    createdAt: "2024-02-01T11:00:00Z",
    updatedAt: "2024-02-01T11:00:00Z"
  },
  {
    id: "PROD-11",
    name: "Patient Portal & Mobile App",
    category: "Cloud Services",
    description: "Portal pasien untuk akses rekam medis, booking appointment, lihat hasil lab, pembayaran online, dan rating layanan.",
    price: 110000000,
    stock: 65,
    sold: 73,
    features: [
      "Personal Health Record Access",
      "Online Appointment Booking",
      "Lab & Radiology Results",
      "E-Prescription History",
      "Online Payment",
      "Hospital Navigation",
      "Health Tips & Articles",
      "Family Member Management",
      "Rating & Feedback",
      "Multi-language Support"
    ],
    createdAt: "2024-02-05T12:00:00Z",
    updatedAt: "2024-02-05T12:00:00Z"
  },
  {
    id: "PROD-12",
    name: "ICU Monitoring System",
    category: "Hospital Management",
    description: "Sistem monitoring pasien ICU real-time. Integrasi dengan vital sign monitors dan ventilator. Critical alert management.",
    price: 280000000,
    stock: 30,
    sold: 38,
    features: [
      "Real-time Vital Signs Monitor",
      "Ventilator Integration",
      "Infusion Pump Management",
      "Critical Alert System",
      "Trend Analysis & Charts",
      "Nurse Call Integration",
      "Medication Administration Record",
      "Fluid Balance Calculation",
      "Remote Monitoring Dashboard",
      "HL7/FHIR Device Interface"
    ],
    createdAt: "2024-02-08T13:30:00Z",
    updatedAt: "2024-02-08T13:30:00Z"
  },
  {
    id: "PROD-13",
    name: "Business Intelligence & Analytics",
    category: "Hospital Management",
    description: "Dashboard analytics untuk manajemen RS. KPI tracking, financial analysis, operational metrics, dan predictive analytics.",
    price: 165000000,
    stock: 55,
    sold: 61,
    features: [
      "Executive Dashboard",
      "Financial Analytics",
      "Operational KPIs",
      "Patient Flow Analysis",
      "Revenue Cycle Management",
      "Bed Occupancy Tracking",
      "Doctor Performance Metrics",
      "Predictive Analytics",
      "Custom Report Builder",
      "Export to Excel/PDF"
    ],
    createdAt: "2024-02-10T14:00:00Z",
    updatedAt: "2024-02-10T14:00:00Z"
  },
  {
    id: "PROD-14",
    name: "Training & Implementation Package",
    category: "Training & Support",
    description: "Paket pelatihan lengkap untuk staff RS dalam menggunakan HMS. Termasuk on-site training, dokumentasi, dan sertifikasi.",
    price: 50000000,
    stock: 200,
    sold: 156,
    features: [
      "On-site Training (5 hari)",
      "User Manual & Documentation",
      "Video Tutorial Library",
      "Hands-on Practice Session",
      "Admin & Super User Training",
      "Certification Program",
      "Train the Trainer",
      "Post-training Support (3 bulan)",
      "Online Learning Portal",
      "Customized Training Materials"
    ],
    createdAt: "2024-02-12T15:00:00Z",
    updatedAt: "2024-02-12T15:00:00Z"
  },
  {
    id: "PROD-15",
    name: "Cloud Hosting - Premium Tier",
    category: "Cloud Services",
    description: "Cloud hosting dengan SLA 99.9% uptime. Automatic backup, disaster recovery, dan 24/7 monitoring. Berbasis Oracle Cloud Infrastructure.",
    price: 45000000,
    stock: 100,
    sold: 128,
    features: [
      "99.9% SLA Uptime Guarantee",
      "Daily Automatic Backup",
      "Disaster Recovery Plan",
      "24/7 Server Monitoring",
      "DDoS Protection",
      "SSL Certificate Included",
      "CDN for Fast Access",
      "Scalable Resources",
      "Dedicated Support Team",
      "Oracle Cloud Infrastructure"
    ],
    createdAt: "2024-02-15T16:00:00Z",
    updatedAt: "2024-02-15T16:00:00Z"
  },
  {
    id: "PROD-16",
    name: "BPJS Bridging System",
    category: "Integration",
    description: "Modul integrasi lengkap dengan sistem BPJS Kesehatan. V-Claim, P-Care, E-Klaim, dan monitoring eligibilitas peserta real-time.",
    price: 90000000,
    stock: 85,
    sold: 98,
    features: [
      "V-Claim Integration",
      "P-Care for Faskes 1",
      "E-Klaim Submission",
      "Peserta Eligibility Check",
      "SEP (Surat Eligibilitas Peserta)",
      "Rujukan Management",
      "Monitoring Klaim Status",
      "Automatic Grouping INA-CBG",
      "Error Handling & Validation",
      "Monthly Reconciliation Report"
    ],
    createdAt: "2024-02-18T17:00:00Z",
    updatedAt: "2024-02-18T17:00:00Z"
  },
  {
    id: "PROD-17",
    name: "Nurse Station Management",
    category: "Hospital Management",
    description: "Sistem untuk nurse station mengelola pasien rawat inap. Vital signs entry, medication administration, dan care planning.",
    price: 135000000,
    stock: 60,
    sold: 55,
    features: [
      "Patient Census & Assignment",
      "Vital Signs Charting",
      "Medication Administration (MAR)",
      "Nursing Care Plan",
      "Intake & Output Monitoring",
      "Wound Care Documentation",
      "Fall Risk Assessment",
      "Pain Management",
      "Shift Handover Notes",
      "Mobile Nursing Cart Support"
    ],
    createdAt: "2024-02-20T09:00:00Z",
    updatedAt: "2024-02-20T09:00:00Z"
  },
  {
    id: "PROD-18",
    name: "Inventory & Procurement System",
    category: "Hospital Management",
    description: "Sistem manajemen inventory dan procurement untuk logistik RS. Multi-warehouse, automatic reorder, dan vendor management.",
    price: 125000000,
    stock: 70,
    sold: 64,
    features: [
      "Multi-warehouse Management",
      "Automatic Reorder Point",
      "Purchase Order & Approval",
      "Vendor Management",
      "Receiving & Quality Check",
      "Stock Opname",
      "Expiry Date Alert",
      "FIFO/FEFO Tracking",
      "Cost Analysis & Reporting",
      "Integration with Finance"
    ],
    createdAt: "2024-02-22T10:00:00Z",
    updatedAt: "2024-02-22T10:00:00Z"
  }
];
